TimeTracker/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post "/login" => "sessions#create", as: "login"
  get "/login" => "sessions#new"
  delete "/logout" => "sessions#destroy", as: "logout"

  patch "/tasks/:task_id/timeentries/:id/restart" => "timeentries#start", as: "start_timer"

  resources :users, only: [:new, :create]

  resources :tasks do
    resources :timeentries
  end

  resources :customers do
    resources :projects 
  end

end

TimeTracker/app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :projects
end

TimeTracker/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_many :timeentries
  has_many :tasks
end

TimeTracker/app/models/task.rb
class Task < ActiveRecord::Base
	has_one :timeentry
	belongs_to :project

	def self.total(user)
		all_te = Timeentry.where(user_id: user.id)
		durations = []
		all_te.each do |te|
			durations << te.duration
		end
		durations.delete(nil)
		sum = durations.inject{ |sum,x| sum += x}
		
		Time.at(sum).gmtime.strftime('%R:%S') if sum != nil
	end
end

TimeTracker/app/models/timeentry.rb
class Timeentry < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :task
end

TimeTracker/app/models/user.rb
class User < ActiveRecord::Base
	has_many :timeentries

	validates :password, confirmation: true
	validates :password_confirmation, presence: true

	attr_reader :entered_password

	def password
		@password ||= BCrypt::Password.new(password_hash)
	end

	def password=(new_password)
		@entered_password = new_password
		@password = BCrypt::Password.create(new_password)
		self.password_hash = @password
	end

	def self.authenticate(email, password)
		user = User.find_by_email(email)
		return user if user && (user.password == password)
		nil
	end
end

TimeTracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  helper_method :current_user, :logged_in?

  protect_from_forgery with: :exception

  def current_user
  	@user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!(session[:user_id].nil?)
 	end
end

TimeTracker/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		redirect_to root_path if logged_in? == false
		@customers = Customer.all
	end
	def show
		@projects = Project.where(customer_id: params[:id])
	end
end

TimeTracker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@customer = Customer.find(params[:customer_id])		
		
	end

	def new
		@customer = Customer.find(params[:customer_id])
		@project = Project.new
	end

	def create
		@customer = Customer.find(params[:customer_id])
		@project = Project.new(project_params)
		@project.customer_id = @customer.id
		@project.save
		redirect_to customer_projects_path(@customer)
	end

	private
	def project_params
		params.require(:project).permit(:project_name)
	end
end

TimeTracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if logged_in?
			redirect_to root_path
		else
			@session = nil		
		end
	end

	def create
		user = User.authenticate(params[:user_email], params[:user_password])
		if user
			session[:user_id] = user.id
			redirect_to tasks_path
		else
			flash[:error] = "Invalid email or password"
			render 'new'
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end
end

TimeTracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@tasks = Task.all.reverse
		# @timeentries = Timeentry.where("user_id: current_user.id AND")
	end

	def new
		@task = Task.new
		@projects = Project.all

	end

	def create
		@task = Task.new(task_params)

		@task.save!
		redirect_to tasks_path
	end

	private
	def task_params
		params.require(:task).permit(:task_name, :project_id)
	end
end

TimeTracker/app/controllers/timeentries_controller.rb
class TimeentriesController < ApplicationController
	def index
		@customers = Customer.all
	end
	def show
		
	end

	def new
		@task = Task.find(params[:task_id])
		if Timeentry.exists?(task_id: @task.id)
			flash[:error] = "Can not create new time entry for same task"
			redirect_to tasks_path
		else
			@timeentry = Timeentry.new(task_id: @task.id)

			render :layout => false
		end
	end

	def edit
		@task = Task.find(params[:task_id])
		@timeentry = Timeentry.find(params[:id])
	end

	def create
		@task = Task.find(params[:task_id])
		start_time = Time.now

		if request.xhr?
			@timeentry = Timeentry.new
			@timeentry.task = @task
			@timeentry.start_time = start_time
			@timeentry.user_id = current_user.id
			@timeentry.note = params[:timeentry][:note]
			@timeentry.save!

			render json: {note: @timeentry.note, id: @timeentry.id, task_id: @task.id}
		end
	end

	def update
		@timeentry = Timeentry.find(params[:id])
		end_time = Time.now
		dur = end_time - (@timeentry.start_time)

		old_dur = @timeentry.duration
		@timeentry.duration = dur + old_dur
		@timeentry.save!
		redirect_to tasks_path

	end

	def start
		@timeentry = Timeentry.find(params[:id])
		start_time = Time.now
		@timeentry.start_time = start_time
		@timeentry.save!

		redirect_to tasks_path
	end

	private
	def timeentry_params
		params.require(:timeentry).permit(:note,:duration,:start_time, :user_id)
	end
end

TimeTracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new	
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to tasks_path
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:username,:display_name,:email,:password,:password_confirmation)
	end

	def redirect_if_logged_in
		redirect_to root_path if logged_in?
	end
end

TimeTracker/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

TimeTracker/app/helpers/application_helper.rb
module ApplicationHelper
end

TimeTracker/app/helpers/customers_helper.rb
module CustomersHelper
end

TimeTracker/app/helpers/projects_helper.rb
module ProjectsHelper
end

TimeTracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

TimeTracker/app/helpers/tasks_helper.rb
module TasksHelper
end

TimeTracker/app/helpers/timeentry_helper.rb
module TimeentryHelper
end

TimeTracker/app/helpers/users_helper.rb
module UsersHelper
end

TimeTracker/app/helpers/welcome_helper.rb
module WelcomeHelper
end

TimeTracker/app/views/customers/index.html.erb
<h1>Welcome <%= current_user.username %></h1>
<br><%= link_to 'Back', root_path %>

<% @customers.each do |customer| %>
<ul>
	<li><%= link_to "#{customer.company}", customer_projects_path(customer)  %></li>
</ul>
<% end %>

TimeTracker/app/views/customers/show.html.erb
<h1>Projects</h1>

<% @projects.each do |project| %>
	<%= link_to project.project_name, tasks_path  %>
<% end %>

TimeTracker/app/views/projects/index.html.erb
<h1>Projects</h1>


<h3><%= @customer.company %></h3>
<ul>
	<li><%= @customer.city %></li>
	<li><%= @customer.phone1 %></li>
</ul>

<br><%= link_to 'New Project', new_customer_project_path(@customer) %>

<% @customer.projects.each do |p| %>
	<h4><%= p.project_name %></h4>
<% end %>

<%= link_to 'Go To Tasks', tasks_path %>

TimeTracker/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for ([@customer, @customer.projects.build]) do |f|%>
	<br><%= f.text_field :project_name, placeholder: 'Project Name' %>

	<p>
		<%= f.submit %>
	</p>

<% end %>

TimeTracker/app/views/tasks/index.html.erb
<h1>Tasks</h1>
<h2>Welcome <%= current_user.username %></h2>
<br><%= link_to 'Back', root_path %>


<% if flash[:error] %>

	<p>
		<%= flash[:error] %>
	</p>
	
<% end %>

<div class="cr_teshow"></div>
	
<p>
	<%= Time.now.strftime("%A, %B %e") %>
</p>

<p>
	<%= link_to 'New Task', new_task_path, id: "new_task_btn" %>
</p>

	<% @tasks.each do |t| %>
<table>
	<tr>
		<th><div class="task"> <%= t.task_name %>(<%= t.project.project_name %>)</div></th>
		<th>Duration</th>
	</tr>
	<tr>
		<% if t.timeentry != nil %>
			
		<td><div class="note1"><div class="note"> <%= t.timeentry.note %></div></div></td>
		<td><%= t.timeentry.duration %></td>

		<% else %>
		<td><div class="note1">note</div></td>
		<td>0</td>
		<% end %>
		
		<td><%= link_to 'Start', new_task_timeentry_path(t), id: "start_btn" %></td>
		<% if t.timeentry != nil %>
		<td><%= link_to 'Edit', edit_task_timeentry_path(task_id: t.id, id: t.timeentry.id), id: "edit_btn" %></td>

		<% end %>
	</tr>
</table>
	<% end %>

<h3><div class="total"> Total:<%= Task.total(current_user) %></div></h3>

TimeTracker/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for @task do |f| %>

	<p>
		<% projects_array = @projects.map {|prjct| [prjct.project_name, prjct.id]} %>
		<%= f.select :project_id, options_for_select(projects_array) %>
	</p>

	<p>
		<%= f.text_field :task_name, placeholder: "task_name" %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

TimeTracker/app/views/timeentries/edit.html.erb
<h1>Edit</h1>

<% if flash[:error] %>
	<p>
		<%= flash[:error] %>
	</p>
	
<% end %>


<br>Start Time:<%= @timeentry.start_time %>
<br>Duration:<%= @timeentry.duration %>
<br>
<br><%= @timeentry.note %>


<%= form_for ([@timeentry.task, @timeentry]) do |f| %>

	<p>
		<%= f.submit 'Stop' %>
	</p>

	<p>
		<%= link_to 'Restart Timer', start_timer_path, method: :patch %>
	</p>
<% end %>

TimeTracker/app/views/timeentries/new.html.erb
<h1>New Time Entry</h1>

<div class="stopwatch">
	
</div>



<div class="cr_timeentry">
<%= form_for ([@task, @task.build_timeentry]) do |f| %>

	<p>
		<%= f.text_area :note, placeholder: 'note' %>
	</p>

	<p>
		<%= f.submit 'Start Timer'%>
	</p>
<% end %>

</div>

TimeTracker/app/views/users/new.html.erb
<h1>New User</h1>

<div class="wrap-center">

<% if @user.errors.any? %>
	<div id="error_expl">
	<%= pluralize(@user.errors.count, "error") %>
	prohibited user from being created:
	<% @user.errors.full_messages.each do |msg| %>
		<ul>
			<li><%= msg %></li>
		</ul>
	<% end %>
	</div>
<% end %>

<%= form_for @user do |f| %>

	<br><%= f.text_field :username, placeholder: 'name' %>
	
	<br><%= f.text_field :display_name, placeholder: 'display name' %>
	
	<br><%= f.text_field :email, placeholder: 'email' %>

	<br><%= f.password_field :password, placeholder: 'password' %>

	<br><%= f.password_field :password_confirmation, placeholder: 'password confirmation' %>
	
	<br>
	<br><%= f.submit 'Sign Up' %>

	<br>
<% end %>

</div>

TimeTracker/app/views/welcome/index.html.erb
<h1>Innova TimeTracker</h1>
<p>yahoooo!</p>

<p>
	<%= link_to 'Customers Index', customers_path %>
</p>

<p>
	<%= link_to 'Tasks Index', tasks_path %>
</p>